# The Tatami menu, after Omarchy 4's default/omarchy/omarchy-menu.jsonc
# (MIT, see ../../../LICENSE.omarchy) without its Arch package, update and theme
# entries. Entries run the `tatami` helper; Escape returns to the parent.
name = "tatami"
name_pretty = "Tatami"
fixed_order = true
hide_from_providerlist = true
action = "%VALUE%"

[[entries]]
text = "Apps"
icon = "󰀻"
value = "tatami apps"
keywords = ["app", "applications"]

[[entries]]
text = "Learn"
icon = "󰧑"
submenu = "tatami-learn"

[[entries]]
text = "Trigger"
icon = "󱓞"
submenu = "tatami-trigger"

[[entries]]
text = "Setup"
icon = ""
submenu = "tatami-setup"
keywords = ["settings"]

[[entries]]
text = "About"
icon = ""
value = "tatami about"

[[entries]]
text = "System"
icon = ""
submenu = "tatami-system"
keywords = ["power-menu"]
